name: deploy
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add the ssh key
        run: echo ${{ secrets.SSH_PRIVATE_KEY }} >> ~/.ssh/id_rsa

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Write text file with scp maybe
        run: scp hi.txt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/test

