name: Super-Linter

on: workflow_dispatch

jobs:
  super-lint:
    name: Lint code base
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: SSH into Host
        run: |
          ssh root:${{ secrets.SSH_HOST }} "ls"
        
          
